version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: foodgram
      POSTGRES_PASSWORD: foodgram
      POSTGRES_DB: foodgram
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ../.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
